document_root: www
behat_path: tests
docker_compose:
  overrides:

hooks:
  build: |
    drush dl drupal-7.39
    mv drupal-7.39 www

    cd www/profiles
    git clone https://github.com/proudcity/proud.git
    cd proud
    drush verify-makefile drupal-org.make
    drush make --no-cache --drupal-org drupal-org.make .

    cd ../../sites/all/modules
    mkdir apps
    #mkdir dev
    mkdir contrib
    mkdir custom
    cd apps
    git clone https://github.com/proudcity/proud_faq.git
    git clone https://github.com/proudcity/proud_event.git
    git clone https://github.com/proudcity/proud_landingpage.git
    git clone https://github.com/proudcity/proud_news.git
    git clone https://github.com/proudcity/proud_webform.git
    git clone https://github.com/proudcity/proud_people.git
    git clone https://github.com/proudcity/proud_agency.git
    git clone https://github.com/proudcity/proud_document.git
    git clone https://github.com/proudcity/proud_social.git
    git clone https://github.com/proudcity/proud_search.git
    #cd ../dev
    #git clone --branch 7.x-1.x http://git.drupal.org/project/angular_media.git
    #git clone --branch 7.x-1.x http://git.drupal.org/project/media_formatters.git
    #git clone --branch 7.x-1.x http://git.drupal.org/project/ckeditor_widgets.git
    #git clone --branch 7.x-1.x http://git.drupal.org/project/ckeditor_filter.git
    #git clone --branch 7.x-1.x http://git.drupal.org/sandbox/jlyon/socialfield_widgets.git social_field_widgets
    #git clone --branch 7.x-1.x http://git.drupal.org/sandbox/jlyon/2564675.git google_analytics_embed
    #git clone --branch 7.x-1.x http://git.drupal.org/sandbox/jlyon/2564689.git bootstrap_fieldable_panel_panes
    cd ../custom
    #git@github.com:proudcity/proudcity_demo.git

    mkdir ../../themes/dev
    cd ../../themes/dev
    #git clone --branch 7.x-1.x http://git.drupal.org/project/minimalist_admin.git

    cd ../../../../
    rm *.git

  enable_first: |
    #drush {{alias}} site-install proud --db-url=mysql://drupal:drupal@database/drupal --sites-subdir=default -y
