document_root: www
behat_path: tests
docker_compose:
  overrides:

hooks:
  build: |
    git clone https://github.com/proudcity/proud-drops.git www

    cd www/sites/all/modules
    mkdir apps
    #mkdir dev
    #mkdir contrib
    #mkdir custom
    cd apps
    git clone --branch 7.x-1.x https://github.com/proudcity/proud_311_app.git
    git clone --branch 7.x-1.x https://github.com/proudcity/proud_map_app.git
    #cd ../dev
    #git clone --branch 7.x-1.x http://git.drupal.org/project/angular_media.git
    #git clone --branch 7.x-1.x http://git.drupal.org/project/media_formatters.git
    #git clone --branch 7.x-1.x http://git.drupal.org/project/ckeditor_widgets.git
    #git clone --branch 7.x-1.x http://git.drupal.org/project/ckeditor_filter.git
    #git clone --branch 7.x-1.x http://git.drupal.org/sandbox/jlyon/socialfield_widgets.git social_field_widgets
    #git clone --branch 7.x-1.x http://git.drupal.org/sandbox/jlyon/2564675.git google_analytics_embed
    #git clone --branch 7.x-1.x http://git.drupal.org/sandbox/jlyon/2564689.git bootstrap_fieldable_panel_panes
    #cd ../custom
    #git@github.com:proudcity/proudcity_demo.git

    cd ../../../../
    mkdir sites/all/themes/custom
    #git clone --branch 7.x-1.x http://git.drupal.org/project/minimalist_admin.git

  enable_first: |
    drush {{alias}} site-install proud --db-url=mysql://drupal:drupal@database/drupal --sites-subdir=default -y
